### ISSUE TITLE
Erreurs 404 & problèmes de CSS

### ISSUE THREAD

**Issue by Rhynchocephale** [Nomelihp/Opium#1]
- Sur la page Présentation, le CSS déconne.
- Sur Tutoriels & Glossaire, il n'y a carrément pas de CSS.
- Depuis l'Accueil (Index), cliquer sur la tête de bonhomme à-côté du logo nous renvoie une 404 au lieu de Login, alors que depuis les autres pages, ça va.
- Cliquer sur l'onglet "Mes chantiers" depuis "Mes chantiers" fait une 404. Idem sur "Nouveau chantier". Depuis Index, par contre, pas de problème.

**Comment by mohamedamjad** [comment]
Bugs corrigés dans le commit 
https://github.com/Nomelihp/Opium/commit/01232f0c80b4569f925b7fd5258b22394686b0d8
