### ISSUE TITLE
besoins.json & calibration

### ISSUE THREAD

**Issue by Rhynchocephale** [Nomelihp/Opium#17]
Dans le cas où ce n'est pas l'autocalibration qui a été sélectionnée, il y a moyen de choper quelque part le nom du fichier de calibration utilisé ?

**Comment by mohamedamjad** [comment]
Comme j'ai mentionné dans https://github.com/Nomelihp/Opium/issues/15#issuecomment-94164843
Le fichier de calibration serait le seul dans le répertoire Ori-Calib
