### ISSUE TITLE
Notification métier

### ISSUE THREAD

**Issue by cwamgis** [Nomelihp/Opium#25]
maintenant que Philémon envoie l'état = 2 depuis l'interface, notifier le module métier depuis nouveau_chantier.js

**Comment by cwamgis** [comment]
je notifie le module métier, mais je suis par sûr qu'il m'entende... Amjad?

**Comment by mohamedamjad** [comment]
Je ne trouve pas la foction de notification dans nouveau_chantier.js .. Régis?

**Comment by cwamgis** [comment]
fait par Amjad f65a44227f7720b833f4a14588129cb4119dc60a
