### ISSUE TITLE
Récupérer les json dans le js

### ISSUE THREAD

**Issue by Rhynchocephale** [Nomelihp/Opium#26]
J'ai besoin d'avoir accès à besoins.json dans infoImages.js. Comment je fais pour récupérer ça ?

**Comment by cwamgis** [comment]
je t'ai préparée une petite fonction=> infosChantier(idChantier,callback) déclarée dans infosChantier.js, tu m'en diras des nouvelles.
Elle est déjà importée depuis nouveau_chantier.ejs
Tu lui passes l'id de chantier et le callback que tu veux exécuter une fois les données récupérées auprès du serveur. Ce callback récupère req (objet xmlhttprequest)

Exemple d'appel (dans chantier.js): 
infosChantier(idChantier,function(req){
        var toto = JSON.parse(req.responseText);
              // Pour mettre à jour l'interface....
    });
