### ISSUE TITLE
Ajouter les thumbnails dans le chargement d'images

### ISSUE THREAD

**Issue by mohamedamjad** [Nomelihp/Opium#3]
Besoin du product owner:
- lorsque les images chargent, le product owner veut voir les thumbnails(miniatures) dans l'espace de chargement

**Comment by cwamgis** [comment]
au final, vous avez décidé quoi la dessus hier?

**Comment by Rhynchocephale** [comment]
Si on le fait, c'est bien, si on le fait pas, c'est pas grave. On essaie d'avoir un rendu qui fonctionne plutôt qu'un rendu qui soit hyper-joli mais bancal.

**Comment by mohamedamjad** [comment]
Le product owner est OK pour ne pas prioriser cette tâche
