### ISSUE TITLE
la page chantiers plante

### ISSUE THREAD

**Issue by mohamedamjad** [Nomelihp/Opium#31]
La page chantier sort un message d'erreur
/home/anonymous/ENSG/LastProject/Opium/maitre/utilisateur/views/chantiers.ejs:13 11| </ul> 12| </div> >> 13| </div> 14| 15| </div> 16| </div> chantier is not defined

**Comment by Rhynchocephale** [comment]
Je ne comprends pas l'erreur, c'est comme s'il ne connaissait plus la variable _chantiers_. Quelqu'un a touché aux routes, peut-être ?
**Edit** : ok je crois que j'ai trouvé, une modif que j'ai faite mais que j'avais pas dû pusher. Je teste ça.
**Re-edit** : j'ai l'impression que plein de modifs que j'ai faites ont viré. J'aime pas trop trop beaucoup ça. Je préfère quand ça fait un peu plus moins n'importe quoi.

**Comment by Rhynchocephale** [comment]
Sur [mon profil](https://github.com/cdrouadaine) on peut voir que je n'ai fait aucune contribution aujourd'hui. J'aime ce qu'il se passe.

**Comment by Rhynchocephale** [comment]
C'est d'autant plus étrange que j'ai vu que Philémon avait sur son ordi des modifs que j'avais faites. Je pige vraiment pas. [Mon ordi a peut-être un virus.](https://xkcd.com/1180/)

Réparé, au fait.
