### ISSUE TITLE
Test exécution MongoDB

### ISSUE THREAD

**Issue by hmouthier** [Nomelihp/Opium#4]
Pour Régis, peux-tu tester l'executable de mongod sur ton windows 32bits stp.

**Comment by cwamgis** [comment]
j'y pense!

**Comment by cwamgis** [comment]
marche pô
![a_fac](https://cloud.githubusercontent.com/assets/9267241/7219363/ff0e468e-e69b-11e4-97d6-ea429d382a42.png)
