### ISSUE TITLE
La fonctionnalité d'ajout d'un utilisateur ne fonctionne pas.

### ISSUE THREAD

**Issue by ebardiere** [Nomelihp/Opium#46]
http://172.31.43.52:3000/nouvel_utilisateur

**Comment by Rhynchocephale** [comment]
Les boutons sont là pour plus tard, si quelqu'un veut développer un système de login. Ça ne fait pas partie de ce qui nous a été demandé.
Résolution partielle : les boutons n'ont désormais plus d'effet lorsque l'on clique dessus.
