### ISSUE TITLE
Pb Upload images ...

### ISSUE THREAD

**Issue by ebardiere** [Nomelihp/Opium#56]
L'upload des images ne fonctionne pas.... ou plus.

**Comment by cdrouadaine** [comment]
Je viens de rallumer l'ordinateur sur lequel vous aviez fait la démo et sur ce dernier l'envoi des images fonctionne...

**Comment by mohamedamjad** [comment]
J'ai testé aujourd'hui ça marche,.. C'est peut être l'ordi de tests à la salle qui a crashé !?
