### ISSUE TITLE
Problème connexion à la base de données

### ISSUE THREAD

**Issue by Nomelihp** [Nomelihp/Opium#8]
Quand je lance le serveur sur windows 8 (avec "node ./bin/www") ou que je fais "node mogo_config.js" dans model, j'obtiens l'erreur :
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

**Comment by Rhynchocephale** [comment]
> Quand je lance le serveur sur
> 
> # **_WINDOWS 8_**
> 
> (avec "node ./bin/www") ou que je fais "node mogo_config.js" > dans model, j'obtiens l'erreur :
> { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
> js-bson: Failed to load c++ bson extension, using pure JS version

Je crois que j'ai une vague idée de l'origine de l'erreur.

**Comment by mohamedamjad** [comment]
Si t'as une vague idée.. crache la

**Comment by Rhynchocephale** [comment]
Ah mince, j'ai pas écrit Windows 8 en assez gros, l'ironie n'était pas assez visible.
